project_id = "hzguwuofnvkgeveorixs"

[functions.enviar-contato]
verify_jwt = false

[functions.enviar-notificacao]
verify_jwt = false

[functions.gerar-ficha-pdf]
verify_jwt = true

[functions.gerar-dados-ficticios]
verify_jwt = true

[functions.limpar-dados]
verify_jwt = true

[functions.gerar-comprovante]
verify_jwt = true

[functions.verificar-prazos]
verify_jwt = false

[functions.manifest-pwa]
verify_jwt = false


[functions.admin-usuarios]
verify_jwt = false

[functions.validar-captcha]
verify_jwt = false

[functions.recalcular-fila]
verify_jwt = false

[functions.registrar-auditoria]
verify_jwt = false

[functions.setup-projeto]
verify_jwt = false

[functions.get-maps-key]
verify_jwt = false

[functions.send-email]
verify_jwt = false
