/* PONTE: expõe nomes de ícones (estilo lucide-react) usando Bootstrap Icons.
   O alias "lucide-react" do vite.config aponta para este arquivo.
   Gerado automaticamente — para alterar mapeamentos edite /tmp/final.js ou aqui o objeto overrides. */
import * as React from "react";
import * as BI from "react-bootstrap-icons";

export type LucideProps = React.SVGProps<SVGSVGElement> & {
  size?: number | string;
  color?: string;
  strokeWidth?: number | string;
  absoluteStrokeWidth?: boolean;
};

export type LucideIcon = React.ForwardRefExoticComponent<
  LucideProps & React.RefAttributes<SVGSVGElement>
>;

const fallback = (BI as any).QuestionCircle;

const createIcon = (biName: string): LucideIcon =>
  React.forwardRef<SVGSVGElement, LucideProps>(
    ({ size, color, strokeWidth, absoluteStrokeWidth, ...props }, ref) => {
      const Cmp = ((BI as any)[biName] || fallback) as React.ComponentType<any>;
      return <Cmp ref={ref as any} size={size as any} color={color} {...(props as any)} />;
    },
  );

export const Activity = createIcon("Activity");
export const AlertCircle = createIcon("ExclamationCircle");
export const AlertTriangle = createIcon("ExclamationTriangle");
export const Apple = createIcon("Apple");
export const Archive = createIcon("Archive");
export const ArchiveRestore = createIcon("ArchiveFill");
export const ArrowDown = createIcon("ArrowDown");
export const ArrowLeft = createIcon("ArrowLeft");
export const ArrowLeftRight = createIcon("ArrowLeftRight");
export const ArrowRight = createIcon("ArrowRight");
export const ArrowRightLeft = createIcon("ArrowLeftRight");
export const ArrowUp = createIcon("ArrowUp");
export const ArrowUpDown = createIcon("ArrowDownUp");
export const Baby = createIcon("PersonHearts");
export const Ban = createIcon("SlashCircle");
export const BarChart3 = createIcon("BarChartFill");
export const Bell = createIcon("Bell");
export const BellOff = createIcon("BellSlash");
export const Bold = createIcon("TypeBold");
export const BookOpen = createIcon("BookHalf");
export const Building = createIcon("Building");
export const Building2 = createIcon("Buildings");
export const Cake = createIcon("Cake");
export const Calendar = createIcon("Calendar");
export const CalendarDays = createIcon("CalendarWeek");
export const CalendarIcon = createIcon("Calendar");
export const CalendarPlus = createIcon("CalendarPlus");
export const Camera = createIcon("Camera");
export const Check = createIcon("Check");
export const CheckCheck = createIcon("CheckAll");
export const CheckCircle = createIcon("CheckCircle");
export const CheckCircle2 = createIcon("CheckCircleFill");
export const ChevronDown = createIcon("ChevronDown");
export const ChevronLeft = createIcon("ChevronLeft");
export const ChevronRight = createIcon("ChevronRight");
export const ChevronUp = createIcon("ChevronUp");
export const ChevronsUpDown = createIcon("ChevronExpand");
export const Circle = createIcon("Circle");
export const ClipboardCheck = createIcon("ClipboardCheck");
export const ClipboardList = createIcon("ClipboardData");
export const Clock = createIcon("Clock");
export const Cloud = createIcon("Cloud");
export const Columns3 = createIcon("LayoutThreeColumns");
export const Copy = createIcon("Files");
export const CreditCard = createIcon("CreditCard");
export const Database = createIcon("Database");
export const Dot = createIcon("Dot");
export const Download = createIcon("Download");
export const Edit = createIcon("Pencil");
export const ExternalLink = createIcon("BoxArrowUpRight");
export const Eye = createIcon("Eye");
export const EyeOff = createIcon("EyeSlash");
export const FileCheck = createIcon("FileEarmarkCheck");
export const FileClock = createIcon("FileEarmarkText");
export const FileDown = createIcon("FileEarmarkArrowDown");
export const FileEdit = createIcon("FileEarmarkText");
export const FileIcon = createIcon("FileEarmark");
export const FileSearch = createIcon("FileEarmarkText");
export const FileSpreadsheet = createIcon("FileEarmarkSpreadsheet");
export const FileText = createIcon("FileEarmarkText");
export const FileWarning = createIcon("FileEarmarkX");
export const FileX = createIcon("FileEarmarkX");
export const Files = createIcon("Files");
export const Filter = createIcon("Funnel");
export const FolderOpen = createIcon("Folder2Open");
export const FormInput = createIcon("InputCursorText");
export const Forward = createIcon("Forward");
export const GalleryHorizontal = createIcon("Images");
export const Globe = createIcon("Globe");
export const GraduationCap = createIcon("MortarboardFill");
export const Grid3x3 = createIcon("Grid3x3");
export const GripVertical = createIcon("GripVertical");
export const Hash = createIcon("Hash");
export const HeartPulse = createIcon("HeartPulse");
export const HelpCircle = createIcon("QuestionCircle");
export const History = createIcon("ClockHistory");
export const Home = createIcon("House");
export const IdCard = createIcon("PersonVcard");
export const Image = createIcon("Image");
export const Inbox = createIcon("Inbox");
export const Info = createIcon("InfoCircle");
export const Italic = createIcon("TypeItalic");
export const Key = createIcon("Key");
export const KeyRound = createIcon("KeyFill");
export const Keyboard = createIcon("Keyboard");
export const Laptop = createIcon("Laptop");
export const Layers = createIcon("Layers");
export const LayoutDashboard = createIcon("Grid1x2Fill");
export const LayoutGrid = createIcon("GridFill");
export const LayoutList = createIcon("ListUl");
export const Lightbulb = createIcon("Lightbulb");
export const Link2 = createIcon("Link45deg");
export const List = createIcon("List");
export const ListOrdered = createIcon("ListOl");
export const Loader2 = createIcon("ArrowRepeat");
export const Lock = createIcon("Lock");
export const LogIn = createIcon("BoxArrowInRight");
export const LogOut = createIcon("BoxArrowRight");
export const Mail = createIcon("Envelope");
export const Map = createIcon("Map");
export const MapPin = createIcon("GeoAlt");
export const Medal = createIcon("Award");
export const Menu = createIcon("List");
export const MessageCircle = createIcon("ChatDots");
export const MessageCircleQuestion = createIcon("ChatLeftDots");
export const MessageSquare = createIcon("ChatSquare");
export const MessageSquarePlus = createIcon("ChatLeftText");
export const MessageSquareText = createIcon("ChatSquareText");
export const Monitor = createIcon("Display");
export const MonitorPlay = createIcon("DisplayFill");
export const Moon = createIcon("Moon");
export const MoreHorizontal = createIcon("ThreeDots");
export const MoreVertical = createIcon("ThreeDotsVertical");
export const MousePointer2 = createIcon("Cursor");
export const Navigation = createIcon("Compass");
export const Palette = createIcon("Palette");
export const PanelLeft = createIcon("LayoutSidebar");
export const Paperclip = createIcon("Paperclip");
export const PauseCircle = createIcon("PauseCircle");
export const Pencil = createIcon("Pencil");
export const Phone = createIcon("Telephone");
export const PieChart = createIcon("PieChart");
export const PieChartIcon = createIcon("PieChartFill");
export const Pin = createIcon("Pin");
export const PinOff = createIcon("PinAngle");
export const Play = createIcon("Play");
export const PlayCircle = createIcon("PlayCircle");
export const Plus = createIcon("Plus");
export const Printer = createIcon("Printer");
export const QrCode = createIcon("QrCode");
export const RectangleList = createIcon("ListColumns");
export const RefreshCcw = createIcon("ArrowCounterclockwise");
export const RefreshCw = createIcon("ArrowClockwise");
export const Repeat = createIcon("Repeat");
export const Reply = createIcon("Reply");
export const RotateCcw = createIcon("ArrowCounterclockwise");
export const RotateCw = createIcon("ArrowClockwise");
export const Ruler = createIcon("Rulers");
export const Save = createIcon("Save");
export const Scale = createIcon("Speedometer2");
export const School = createIcon("Building");
export const Search = createIcon("Search");
export const SearchX = createIcon("Search");
export const Send = createIcon("Send");
export const Server = createIcon("Server");
export const Settings = createIcon("Gear");
export const Settings2 = createIcon("GearFill");
export const Share2 = createIcon("Share");
export const Shield = createIcon("Shield");
export const ShieldAlert = createIcon("ShieldExclamation");
export const ShieldCheck = createIcon("ShieldCheck");
export const ShieldOff = createIcon("ShieldSlash");
export const Smartphone = createIcon("Phone");
export const Smile = createIcon("EmojiSmile");
export const Sparkles = createIcon("Stars");
export const Square = createIcon("Square");
export const Star = createIcon("Star");
export const Stethoscope = createIcon("ClipboardPulse");
export const StickyNote = createIcon("StickyFill");
export const Sun = createIcon("Sun");
export const Table = createIcon("Table");
export const Table2 = createIcon("Table");
export const TableProperties = createIcon("Table");
export const Tag = createIcon("Tag");
export const Target = createIcon("Bullseye");
export const Timer = createIcon("Stopwatch");
export const ToggleLeft = createIcon("ToggleOff");
export const ToggleRight = createIcon("ToggleOn");
export const Trash2 = createIcon("Trash");
export const TrendingDown = createIcon("GraphDownArrow");
export const TrendingUp = createIcon("GraphUpArrow");
export const Trophy = createIcon("Trophy");
export const Type = createIcon("Fonts");
export const Unlink = createIcon("Link45deg");
export const Unlock = createIcon("Unlock");
export const Upload = createIcon("Upload");
export const User = createIcon("Person");
export const UserCheck = createIcon("PersonCheck");
export const UserCircle = createIcon("PersonCircle");
export const UserCog = createIcon("PersonGear");
export const UserMinus = createIcon("PersonDash");
export const UserPlus = createIcon("PersonPlus");
export const UserX = createIcon("PersonX");
export const Users = createIcon("People");
export const UsersRound = createIcon("PeopleFill");
export const Variable = createIcon("Braces");
export const Video = createIcon("CameraVideo");
export const VideoOff = createIcon("CameraVideoOff");
export const Volume2 = createIcon("VolumeUp");
export const VolumeX = createIcon("VolumeMute");
export const Webhook = createIcon("Diagram3");
export const Wifi = createIcon("Wifi");
export const WifiOff = createIcon("WifiOff");
export const Workflow = createIcon("Diagram3");
export const Wrench = createIcon("Wrench");
export const X = createIcon("X");
export const XCircle = createIcon("XCircle");
export const Youtube = createIcon("Youtube");
export const Zap = createIcon("Lightning");
export const ZoomIn = createIcon("ZoomIn");
export const ZoomOut = createIcon("ZoomOut");
