INSERT INTO public.campos_inscricao (
  secao,
  nome_campo,
  label,
  tipo,
  placeholder,
  obrigatorio,
  ativo,
  ordem,
  opcoes,
  validacao,
  mascara,
  campo_sistema,
  visivel_responsavel,
  editavel_apos_inscricao,
  dica
)
VALUES
  (
    'crianca',
    'cor_raca_autodeclarada',
    'Cor/raça autodeclarada',
    'select',
    NULL,
    true,
    true,
    40,
    '[{"value":"amarela","label":"Amarela"},{"value":"branca","label":"Branca"},{"value":"indigena","label":"Indígena"},{"value":"parda","label":"Parda"},{"value":"preta","label":"Preta"},{"value":"nao_declarada","label":"Não declarada"}]'::jsonb,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'crianca',
    'cor_raca_certidao',
    'Cor/raça na certidão de nascimento',
    'select',
    NULL,
    true,
    true,
    41,
    '[{"value":"amarela","label":"Amarela"},{"value":"branca","label":"Branca"},{"value":"indigena","label":"Indígena"},{"value":"parda","label":"Parda"},{"value":"preta","label":"Preta"},{"value":"nao_declarada","label":"Não declarada"}]'::jsonb,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'crianca',
    'etnia_indigena',
    'Etnia indígena',
    'select',
    NULL,
    false,
    true,
    42,
    '[{"value":"guarani","label":"Guarani"},{"value":"kaingang","label":"Kaingang"},{"value":"xeta","label":"Xetá"},{"value":"xokleng","label":"Xokleng"},{"value":"outra","label":"Outra"}]'::jsonb,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'crianca',
    'etnia_indigena_outra',
    'Qual etnia',
    'text',
    NULL,
    false,
    true,
    43,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'crianca',
    'quilombo_remanescente',
    'Remanescente de Quilombo?',
    'select',
    NULL,
    true,
    true,
    44,
    '[{"value":"sim","label":"Sim"},{"value":"nao","label":"Não"}]'::jsonb,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'crianca',
    'quilombo_nome',
    'Se sim, qual quilombo',
    'text',
    NULL,
    false,
    true,
    45,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'crianca',
    'nacionalidade',
    'Nacionalidade',
    'select',
    NULL,
    true,
    true,
    46,
    '[{"value":"brasileira","label":"Brasileira"},{"value":"brasileira_naturalizado","label":"Brasileira – nascido no exterior ou naturalizado"},{"value":"estrangeira","label":"Estrangeira"}]'::jsonb,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'crianca',
    'estrangeiro_possui_documentos',
    'Se estrangeiro, possui documentos?',
    'select',
    NULL,
    false,
    true,
    47,
    '[{"value":"sim","label":"Sim"},{"value":"nao","label":"Não"}]'::jsonb,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'crianca',
    'nis',
    'Código de Identificação Social (NIS)',
    'text',
    'Apenas números',
    false,
    true,
    48,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    'Não obrigatório'
  ),
  (
    'endereco',
    'unidade_consumidora',
    'Unidade consumidora (talão de energia)',
    'text',
    NULL,
    true,
    true,
    30,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'endereco',
    'forma_ocupacao_moradia',
    'Forma de ocupação da moradia',
    'select',
    NULL,
    true,
    true,
    31,
    '[{"value":"optou_nao_informar","label":"Optou em não informar"},{"value":"propria","label":"Própria"},{"value":"alugada","label":"Alugada"},{"value":"cedida","label":"Cedida"},{"value":"pensionato","label":"Pensionato"},{"value":"casa_lar_abrigo","label":"Casa lar ou abrigo"},{"value":"outro","label":"Outro"}]'::jsonb,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'endereco',
    'forma_ocupacao_moradia_outro',
    'Se outro, qual',
    'text',
    NULL,
    false,
    true,
    32,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'responsavel_rg',
    'RG/RNE/RME',
    'text',
    'Não obrigatório',
    false,
    true,
    20,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'responsavel_parentesco',
    'O responsável é o quê da criança?',
    'select',
    NULL,
    true,
    true,
    21,
    '[{"value":"pai","label":"Pai"},{"value":"mae","label":"Mãe"},{"value":"avo","label":"Avô"},{"value":"avoa","label":"Avó"},{"value":"tio","label":"Tio"},{"value":"tia","label":"Tia"},{"value":"padrasto","label":"Padrasto"},{"value":"madrasta","label":"Madrasta"},{"value":"irmao","label":"Irmão"},{"value":"irma","label":"Irmã"},{"value":"tutor_legal","label":"Tutor legal"},{"value":"guardiao","label":"Guardião"},{"value":"outro","label":"Outro"}]'::jsonb,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'responsavel_parentesco_outro',
    'Qual parentesco',
    'text',
    NULL,
    false,
    true,
    22,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'responsavel_telefone_comercial',
    'Telefone comercial',
    'phone',
    '(00) 00000-0000',
    false,
    true,
    23,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'filiacao1_nao_declarada',
    'Filiação 1 não declarada',
    'checkbox',
    NULL,
    false,
    true,
    40,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'filiacao1_nome',
    'Filiação 1: nome do pai/mãe',
    'text',
    NULL,
    false,
    true,
    41,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'filiacao1_rg',
    'Filiação 1: RG/RNE/RME',
    'text',
    'Não obrigatório',
    false,
    true,
    42,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'filiacao1_cpf',
    'Filiação 1: CPF',
    'cpf',
    '000.000.000-00',
    false,
    true,
    43,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'filiacao1_email',
    'Filiação 1: e-mail',
    'email',
    'Não obrigatório',
    false,
    true,
    44,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'filiacao1_celular',
    'Filiação 1: celular/WhatsApp',
    'phone',
    '(00) 00000-0000',
    false,
    true,
    45,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'filiacao1_telefone_comercial',
    'Filiação 1: telefone comercial',
    'phone',
    '(00) 00000-0000',
    false,
    true,
    46,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'filiacao2_nao_declarada',
    'Filiação 2 não declarada',
    'checkbox',
    NULL,
    false,
    true,
    50,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'filiacao2_nome',
    'Filiação 2: nome do pai/mãe',
    'text',
    NULL,
    false,
    true,
    51,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'filiacao2_rg',
    'Filiação 2: RG/RNE/RME',
    'text',
    'Não obrigatório',
    false,
    true,
    52,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'filiacao2_cpf',
    'Filiação 2: CPF',
    'cpf',
    '000.000.000-00',
    false,
    true,
    53,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'filiacao2_email',
    'Filiação 2: e-mail',
    'email',
    'Não obrigatório',
    false,
    true,
    54,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'filiacao2_celular',
    'Filiação 2: celular/WhatsApp',
    'phone',
    '(00) 00000-0000',
    false,
    true,
    55,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  ),
  (
    'responsavel',
    'filiacao2_telefone_comercial',
    'Filiação 2: telefone comercial',
    'phone',
    '(00) 00000-0000',
    false,
    true,
    56,
    NULL,
    NULL,
    NULL,
    true,
    true,
    true,
    NULL
  )
ON CONFLICT (nome_campo) DO UPDATE SET
  secao = EXCLUDED.secao,
  label = EXCLUDED.label,
  tipo = EXCLUDED.tipo,
  placeholder = EXCLUDED.placeholder,
  obrigatorio = EXCLUDED.obrigatorio,
  ativo = EXCLUDED.ativo,
  ordem = EXCLUDED.ordem,
  opcoes = EXCLUDED.opcoes,
  validacao = EXCLUDED.validacao,
  mascara = EXCLUDED.mascara,
  campo_sistema = EXCLUDED.campo_sistema,
  visivel_responsavel = EXCLUDED.visivel_responsavel,
  editavel_apos_inscricao = EXCLUDED.editavel_apos_inscricao,
  dica = EXCLUDED.dica;

