// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import { SUPABASE_URL as FALLBACK_URL, SUPABASE_ANON_KEY as FALLBACK_KEY } from '@/config/supabase';

// IMPORTANT: prioritize the persisted original backend credentials over the
// auto-injected env vars, which currently point to an empty Cloud project
// without the real users/data.
export const RESOLVED_SUPABASE_URL = FALLBACK_URL || import.meta.env.VITE_SUPABASE_URL;
export const RESOLVED_SUPABASE_PUBLISHABLE_KEY =
  FALLBACK_KEY ||
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Note: the generated Database types are not currently in sync with the
// connected backend schema, so the client is typed permissively to allow
// table/RPC access across all modules. Replace `any` once types are regenerated.
export const supabase: SupabaseClient = createClient(RESOLVED_SUPABASE_URL, RESOLVED_SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
